version: '2'
services:
  subversion:
    build: .
    image: teamcode/subversion:0.0.2
    container_name: subversion
    hostname: subversion
    volumes:
      - /Users/chiang/tchome/config/httpd:/etc/subversion/httpd
      - /Users/chiang/tchome/data:/var/opt/subversion
      - /Users/chiang/tchome/logs/httpd:/var/log/httpd
    ports:
      - 9999:80
    environment:
      TZ: "Asia/Seoul"
    entrypoint: /opt/subversion/assets/entrypoint.sh
